# Generated by Django 4.2.21 on 2025-05-29 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_cidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('dataDeNascimento', models.DateField(verbose_name='Data de nascimento')),
                ('email', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=20)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alunos.cidade')),
            ],
        ),
    ]
